package com.pulko.siurana.tool
import grails.artefact.Artefact;

@Artefact("TagLibrary")
class MainMenuTagLib {
	static namespace = "pulko"
	static encodeAsForTags = [tagName: [taglib:'raw']]

	def menu = { attrs, body ->
		if(session.usuario){
			out << "<div class='menu'>"
			out << "	<span>"
			out << "		<ul id='nav'>"
			out << "			<li><a href='/Siurana/'>Inicio</a></li>"
			out << "			<li><a href='#'>Gestores</a>"
			out << "				<div class='subs'>"
			out << "					<div>"
			out << "						<ul>"
			out << "							<li><h3>Principales</h3>"
			out << "								<ul>"
			out << "									<li><a href='/Siurana/usuario/index'>Usuario</a></li>"
			out << "									<li><a href='/Siurana/rol/index'>Roles</a></li>"
			out << "									<li><a href='/Siurana/perfil/index'>Perfiles</a></li>"
			out << "									<li><a href='/Siurana/asistencia/index'>Asistencias</a></li>"
			out << "								</ul></li>"
			out << "							<li><h3>Utiles</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Link 6</a></li>"
			out << "									<li><a href='#'>Link 7</a></li>"
			out << "									<li><a href='#'>Link 8</a></li>"
			out << "								</ul></li>"
			out << "						</ul>"
			out << "					</div>"
			out << "				</div></li>"
			out << "				<li><a href='#'>Tienda</a>"
			out << "				<div class='subs'>"
			out << "					<div>"
			out << "						<ul>"
			out << "							<li><h3>Palestra</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Ropa</a></li>"
			out << "									<li><a href='#'>Magnecio</a></li>"
			out << "								</ul></li>"
			out << "							<li><h3>Terceros</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Mercaderias</a></li>"
			out << "								</ul></li>"
			out << "						</ul>"
			out << "					</div>"
			out << "				</div></li>"
			out << "			<li><a href='#'>Reportes</a>"
			out << "				<div class='subs'>"
			out << "					<div class='wrp2'>"
			out << "						<ul>"
			out << "							<li><h3>Usuarios</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Link 1</a></li>"
			out << "									<li><a href='#'>Link 2</a></li>"
			out << "									<li><a href='#'>Link 3</a></li>"
			out << "									<li><a href='#'>Link 4</a></li>"
			out << "									<li><a href='#'>Link 5</a></li>"
			out << "								</ul></li>"
			out << "							<li><h3>Asistencias</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Link 6</a></li>"
			out << "									<li><a href='#'>Link 7</a></li>"
			out << "									<li><a href='#'>Link 8</a></li>"
			out << "									<li><a href='#'>Link 9</a></li>"
			out << "									<li><a href='#'>Link 10</a></li>"
			out << "								</ul></li>"
			out << "						</ul>"
			out << "						<p class='sep'></p>"
			out << "						<ul>"
			out << "							<li><h3>Cobros</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Link 11</a></li>"
			out << "									<li><a href='#'>Link 12</a></li>"
			out << "									<li><a href='#'>Link 13</a></li>"
			out << "								</ul></li>"
			out << "							<li><h3>Gastos</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Link 14</a></li>"
			out << "									<li><a href='#'>Link 15</a></li>"
			out << "									<li><a href='#'>Link 16</a></li>"
			out << ""
			out << "								</ul></li>"
			out << "							<li><h3>Estado</h3>"
			out << "								<ul>"
			out << "									<li><a href='#'>Link 17</a></li>"
			out << "									<li><a href='#'>Link 18</a></li>"
			out << "									<li><a href='#'>Link 19</a></li>"
			out << "								</ul></li>"
			out << "						</ul>"
			out << "					</div>"
			out << "				</div></li>					"
			out << "		</ul>"
			out << "	</span>"
			out << "</div>"
		}
	}
}
